---
- name: Start Zoneminder Docker container
  docker_compose:
    project_name: zoneminder
    pull: yes
    recreate: always
    definition:
      version: "2.2"
      services:
        zoneminder:
          container_name: zoneminder
          image: "{{ zoneminder_docker_image }}"
          init: true
          ports:
            - "{{ zoneminder_port }}:80"
          restart: unless-stopped
          shm_size: "{{ zoneminder_shm_size }}"
          volumes:
            - "{{ zoneminder_docker_volumes.events }}:/var/cache/zoneminder/events"
            - "{{ zoneminder_docker_volumes.images }}:/var/cache/zoneminder/images"
            - "{{ zoneminder_docker_volumes.mysql }}:/var/lib/mysql"
