---
- name: Start Zoneminder Docker container
  docker_service:
    project_name: zoneminder
    pull: yes
    definition:
      version: "2"
      services:
        zoneminder:
          container_name: zoneminder
          image: "{{ zoneminder_docker_image }}"
          ports:
            - "{{ zoneminder_port }}:80"
          restart: always
          tmpfs: /tmp/zoneminder-tmpfs
          volumes:
            - "{{ zoneminder_docker_volumes.events }}:/var/cache/zoneminder/events"
            - "{{ zoneminder_docker_volumes.images }}:/var/cache/zoneminder/images"
            - "{{ zoneminder_docker_volumes.mysql }}:/var/lib/mysql"
