---
- name: Start Zoneminder Docker container
  docker_service:
    project_name: zoneminder
    pull: yes
    definition:
      version: "2.2"
      services:
        zoneminder:
          container_name: zoneminder
          image: "{{ zoneminder_docker_image }}"
          init: true
          ports:
            - "{{ zoneminder_port }}:80"
          restart: on-failure
          volumes:
            - "{{ zoneminder_docker_volumes.events }}:/var/lib/zoneminder/events"
            - "{{ zoneminder_docker_volumes.images }}:/var/lib/zoneminder/images"
            - "{{ zoneminder_docker_volumes.mysql }}:/var/lib/mysql"
