---
- name: Create Docker volume directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  become: true
  with_items: "{{ docker_volumes.values() }}"

- name: Start Zoneminder Docker container
  docker_service:
    build: no
    project_name: zoneminder
    definition:
      version: "2"
      services:
        zoneminder:
          container_name: zoneminder
          image: "{{ zoneminder_docker_image }}"
          ports:
            - "{{ zoneminder_port }}:80"
          restart: always
          volumes:
            - "{{ docker_volumes.zoneminder_events }}:/var/lib/zoneminder/events"
            - "{{ docker_volumes.zoneminder_images }}:/var/lib/zoneminder/images"
            - "{{ docker_volumes.zoneminder_mysql }}:/var/lib/mysql"
